---
- name: Perform software update on node - "{{host1}}"
  hosts: "host1"
  gather_facts: false
  vars:

  tasks:

   - name: install the latest version of Apache
     yum:
       name: httpd
       state: latest
     become: yes
